---
HOST: http://localhost:6900
WEBHOOK_URL: http://localhost:6900/webhook
PORT: 6900
GITHUB_CLIENT_ID: {{ GITHUB_CLIENT_ID }}
GITHUB_CLIENT_SECRET: {{ GITHUB_CLIENT_SECRET }}
TEAMBITION_HOST: https://www.teambition.com
TEAMBITION_MESSAGE_ROBOT_KEY: {{ TEAMBITION_MESSAGE_ROBOT_KEY }}
MONGODB:
  URL: mongodb://localhost/demo
  USE_SSL: false
  KEY_PATH:
  CERT_PATH:
  CA_PATH: